baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'terminal'

# Publishing control
buildFuture = false  # Build posts with publishDate in the future

[params]
  contentTypeName = "posts"
  themeColor = "orange"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = false

[caches]
  [caches.images]
    dir = ':cacheDir/images'